
-- LISTAGG 1
SELECT LISTAGG(NAME, ', ') WITHIN GROUP (ORDER BY ID);

-- LISTAGG 2
SELECT LISTAGG(COALESCE(NAME, 'null'), ', ') WITHIN GROUP (ORDER BY ID);

-- LISTAGG 3
SELECT LISTAGG(ID, ', ') WITHIN GROUP (ORDER BY ID) OVER (ORDER BY ID);

-- ARRAY_AGG 1
SELECT ARRAY_AGG(NAME ORDER BY ID);

-- ARRAY_AGG 2
SELECT ARRAY_AGG(NAME ORDER BY ID) FILTER (WHERE NAME IS NOT NULL);

-- ARRAY_AGG 3
SELECT ARRAY_AGG(ID ORDER BY ID) OVER (ORDER BY ID);