# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  gradle_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Run Gradle Check
        run: ./gradlew check

  gradle_publish:
    needs: gradle_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'

      - id: install-gradle-properties
        name: Install Gradle Properties from Secret
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
          shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties        

      # create the ASCII armour:
      #    gpg -a --export-secret-keys <key_id> > keyfile.asc
      # then store the content of <keyfile.asc> as github secret <OSSRH_GPG_SECRET_KEY>
      - id: install-secret-key
        name: Install GPG Key from Secret
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --export-secret-keys -o /home/runner/.gnupg/secring.gpg 
          

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}